In [2]:
import numpy as np
z = np.arange(12)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
z = z.reshape(-1,4) # it automatically calculates one dimension,
#if the other dimension is specified and arranges the values
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
z = np.zeros((3,2,4))
z
#This will create three arrays with 2 rows and 4 columns each

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
z = np.ones((2,3,4))
z
# THis will create 2 arrays with 3 rows and 4 columns each

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
z = np.random.normal(0,1,size=(3,4))
z
#THis creates an array having values having mean as 0 and std 1

array([[-1.28732602,  0.11076158,  1.17809959, -0.15146554],
       [ 0.12170553,  1.07447475, -0.18308626,  0.83878538],
       [-0.63417993, -0.93888939,  0.92979423, -0.6780873 ]])

In [9]:
z = np.random.normal(1,2,size=(2,3))
z
# THis creates an array having values having mean as 1 and std 2

array([[-2.52734645, -0.84088202,  1.96590424],
       [ 2.72982883,  0.45467146, -2.44417578]])

In [14]:
X = np.arange(12).reshape(3,4)
Y = np.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Z, Z_ = np.concatenate([X,Y], axis=0), np.concatenate([X,Y], axis=1)
#This concatenates these 2 tensors alongs rows (axis=0) and columns
#(axis=1) respectively
Z
Z_

array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [11]:
X.sum()

66

In [12]:
Y.sum()

30

In [15]:
Z.sum(), Z_.sum()

(96, 96)

In [17]:
a = np.arange(3).reshape(3,1)
b = np.arange(2).reshape(1,2)
print(a,b)
print(a+b)

[[0]
 [1]
 [2]] [[0 1]]
[[0 1]
 [1 2]
 [2 3]]
